### pd.Series (data, index=인덱스)

***data 
- 스칼라(정수, 실수), 리스트, 딕셔너리, ndarray

Series 는 1차원 구조의 자료표현

index가 포함된 numpy의 ndarray

column vector를 표현하는 object

In [26]:
import pandas as pd

In [27]:
pd.Series('banana')

0    banana
dtype: object

In [28]:
pd.Series(41)

0    41
dtype: int64

In [29]:
pd.Series('banana',42)

TypeError: Index(...) must be called with a collection of some kind, 42 was passed

In [31]:
pd.Series('banana',index=[42])

42    banana
dtype: object

#### 대괄호까지 입력해야 함!

In [32]:
pd.Series('banana', index=42)

TypeError: Index(...) must be called with a collection of some kind, 42 was passed

리스트

In [2]:
list_data=[1,2,3,4,5]
list_data

[1, 2, 3, 4, 5]

In [35]:
exl = pd.Series(data=list_data)
exl

0    1
1    2
2    3
3    4
4    5
dtype: int64

*exl 의 type

In [36]:
type(exl)

pandas.core.series.Series

* 데이터들의 타입이 궁금하다면?

In [37]:
exl.dtypes

dtype('int64')

* 몇행 몇열인지 알고싶다면?

In [38]:
exl.shape

(5,)

* shape가 실행되지 않는다면 비슷한 원소의 갯수를 알려주는 size

In [39]:
exl.size

5

* values: ex1에서의 실제 들어가 있는 값만 불러내고 싶을 때

In [40]:
exl.values

array([1, 2, 3, 4, 5], dtype=int64)

In [84]:
exl.keys

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

* type ex1(series)이 갖고 있는 값만 해당하는 타입을 확인하고 싶을 때

In [41]:
type(exl.values)

numpy.ndarray

#### values 값만 보았을때에는 nd array라 하며 
#### 인덱스와 values 값 전체를 보았을 때는 Series라 한다.

인덱스=key 역할 찾기

** 인덱스의 구성 알아보는 법 

In [42]:
exl.index

RangeIndex(start=0, stop=5, step=1)

* range index 형태이며 0부터 5까지 1씩 증가함

* 딕셔너리 구조에서 인덱스 역할을 하는 것은 ? **key**

In [65]:
exl.keys()

RangeIndex(start=0, stop=5, step=1)

##### keys 뒤에 둥근괄호 () 들어감 주의!!

#### 인덱스에 있는 타입을 물어보고싶다면?

In [67]:
type(exl.index)

pandas.core.indexes.range.RangeIndex

##### Series에서는 info() 메소드를 지원하지 않는다! 주의!!

In [66]:
exl.info()

AttributeError: 'Series' object has no attribute 'info'

In [45]:
exl(index=2) 

TypeError: 'Series' object is not callable

In [69]:
exl(2)

TypeError: 'Series' object is not callable

In [70]:
exl[2]

3

In [71]:
exl.index(2)

TypeError: 'RangeIndex' object is not callable

In [72]:
exl.list(2)

AttributeError: 'Series' object has no attribute 'list'

In [73]:
exl(index==2)

NameError: name 'index' is not defined

In [74]:
exl(index=='2')

NameError: name 'index' is not defined

In [75]:
exl(index:2)

SyntaxError: invalid syntax (<ipython-input-75-65be6219e584>, line 1)

In [76]:
exl(index,2)

NameError: name 'index' is not defined

In [77]:
exl.index[2]

2

In [48]:
exl[2]

3

In [49]:
exl.iloc[2]

3

In [50]:
exl.values[2]

3

In [51]:
exl.loc[2]

3

In [52]:
exl.keys()[2]

2

  ndarray로 Series만들기

In [57]:
import numpy as np

In [58]:
np.array([4,3,5,8])

array([4, 3, 5, 8])

In [59]:
pd.Series(data=np.array([4,5,6,8]))

0    4
1    5
2    6
3    8
dtype: int32

In [60]:
np.arange(10,60,10) #60 포함되지 않음XXXX 50까지만 출력됨!!

array([10, 20, 30, 40, 50])

In [61]:
x=pd.Series(np.arange(10,60,10),index = ['a','b','c','d','e'])
x

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [62]:
x.values[0:3]

array([10, 20, 30])

In [63]:
x.loc['a':'c'] #a부터 c까지 

a    10
b    20
c    30
dtype: int32

In [64]:
x.loc[:,'c'] #[행정보,열정보] 이지만 'c'라는  columns를 갖고있지 않아서 error

IndexingError: Too many indexers

In [78]:
x.loc[:'c'] #처음부터~ c까지!!

a    10
b    20
c    30
dtype: int32

In [79]:
x.iloc[0:3]

a    10
b    20
c    30
dtype: int32

In [80]:
x.iloc[:3]

a    10
b    20
c    30
dtype: int32

In [81]:
x[0:3]

a    10
b    20
c    30
dtype: int32

In [82]:
x.loc[0:'c']

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [83]:
x.iloc[0:'c']

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [c] of <class 'str'>

### 딕셔너리

In [ ]:
aa={'a':4, 'b':2,'c':3} #요소는 'key'라함
aa

In [ ]:
b= pd.Series({'a':4, 'b':2,'c':3})

In [ ]:
pd.Series(b)

In [ ]:
pd.Series(data=b)

딕셔너리 구조로 Series를 만들 경우에는 인덱스를 따로 언급하지 않아도 된다.

but, 인덱스를 언급하면 언급한 순서대로 자료가 나열됨

In [ ]:
y= pd.Series(data=b, index = ['b','c','a'])

In [ ]:
pd.Series(data=b, index = ['c','a','b'])

In [ ]:
type(aa)

In [ ]:
type(y)

In [ ]:
y.index

In [ ]:
type(y.index) #y에서 index type만 알고싶다면?

y가 가진 값의 갯수?

In [ ]:
y.size #series 가 가진 원소의 갯수

변수 y의 데이터 타입?

In [ ]:
y.dtypes

변수 y의 3번째 인덱스는?

In [ ]:
y.iloc[2] ### 인덱스가 아니라 값임!!!

In [ ]:
y.index[2] ## <--- 정답

변수 y의 2번째 인덱스는?

In [ ]:
y.keys()[1]

변수 y의 데이터 형태는?

In [ ]:
type(y.values)

변수 y의 데이터 덩어리 2번째 값?

In [ ]:
y.values[1]

In [ ]:
y[1]

In [ ]:
y.iloc[1]

 변수 y의 'b'인덱스가 가진 값?

In [ ]:
y.loc['b']

In [ ]:
y['b']