* 딕셔너리로 데이터프레임 만들기

In [19]:
import pandas as pd
import numpy as np

In [20]:
a = {'one': {'1st':1.0, '2nd':2.0,'3rd':3.0,'4th':4.0},
     'two': {'1st':4.0, '2nd':3.0,'3rd':2.0,'4th':1.0},
     'three': {'1st':5.0, '2nd':6.0,'3rd':7.0,'4th':8.0},
     'four': {'1st':8.0, '2nd':7.0,'3rd':6.0,'4th':5.0} }  

In [21]:
aaa= pd.DataFrame(a)
aaa


one  two  three  four
1st  1.0  4.0    5.0   8.0
2nd  2.0  3.0    6.0   7.0
3rd  3.0  2.0    7.0   6.0
4th  4.0  1.0    8.0   5.0

#### * 딕셔너리에서 열의 순서를 다르게 바꾸어 입력하면? (1열)
#### * 열의 개수를 다르게 넣으면? (3열)
#### * 혼자만 인덱스가 다르면? (4열)

In [22]:
achange = {'one': {'1st':1.0, '4th':2.0,'3rd':3.0,'2nd':4.0},
           'two': {'1st':4.0, '2nd':3.0,'3rd':2.0,'4th':1.0},
           'three': {'2nd':6.0,'3rd':7.0,'4th':8.0},
           'four': {'1st':8.0, '2nd':7.0,'3rd':6.0,'6th':5.0} }  
accc = pd.DataFrame(achange)
accc

one  two  three  four
1st  1.0  4.0    NaN   8.0
4th  2.0  1.0    8.0   NaN
3rd  3.0  2.0    7.0   6.0
2nd  4.0  3.0    6.0   7.0
6th  NaN  NaN    NaN   5.0

* => 데이터가 전체 구조에 맞게 데이터를 재정렬하여 입력됨
* => 비어있는 열의 데이터를 NaN값으로 지정함
* => 다른 자료와 마찬가지로 인덱스의 개수는 동일하게 맞추었으므로
* 오류가 없지만, 새로운 행이 추가되면서 비어있는 행에 데이터를 NaN으로, 
* 새로운 행을 가지지 못한 다른 열들의 데이터값 또한 NaN으로 입력된다

#### 비교: 딕셔너리 VS 리스트

In [23]:
e = [[1.0,2.0,3.0,4.0],
     [4.0,3.0,2.0,1.0],
     [5.0,6.0,7.0,8.0],
     [8.0,7.0,6.0,5.0]]

xyz = pd.DataFrame(e, 
                   index=['1st','2nd','3rd','4th'],
                   columns=['one','two','three','four'])
xyz

one  two  three  four
1st  1.0  2.0    3.0   4.0
2nd  4.0  3.0    2.0   1.0
3rd  5.0  6.0    7.0   8.0
4th  8.0  7.0    6.0   5.0

In [24]:
 xyz.T

1st  2nd  3rd  4th
one    1.0  4.0  5.0  8.0
two    2.0  3.0  6.0  7.0
three  3.0  2.0  7.0  6.0
four   4.0  1.0  8.0  5.0

In [25]:
d = {'one': [1.0,2.0,3.0,4.0],
    'two':  [4.0,3.0,2.0,1.0],
    'three':[5.0,6.0,7.0,8.0],
    'four': [8.0,7.0,6.0,5.0]}

abc = pd.DataFrame(d, 
                   index=['1st','2nd','3rd','4th'],
                   columns=['one','two','three','four'])
abc

one  two  three  four
1st  1.0  4.0    5.0   8.0
2nd  2.0  3.0    6.0   7.0
3rd  3.0  2.0    7.0   6.0
4th  4.0  1.0    8.0   5.0

In [26]:
 aaa.T

1st  2nd  3rd  4th
one    1.0  2.0  3.0  4.0
two    4.0  3.0  2.0  1.0
three  5.0  6.0  7.0  8.0
four   8.0  7.0  6.0  5.0

### 리스트 => 행으로 한 줄 한 줄씩 추가되었음을 확인할 수 있다 

### 딕셔너리 => 열로 하나하나씩 쌓이는 추가되는 구조를 확인 할 수 있다

#### 행과 열의 위치를 바꾸지않고 내부에 입력된 변수들만 전치시키고 싶다면?

#### ====> 변수명.transpose() 메소드 사용

In [27]:
e = np.array(
     [[1.0,2.0,3.0,4.0],
     [4.0,3.0,2.0,1.0],
     [5.0,6.0,7.0,8.0],
     [8.0,7.0,6.0,5.0]] )
xyz2 = pd.DataFrame(e.transpose(),
                   index=['1st','2nd','3rd','4th'],
                   columns=['one','two','three','four'])

xyz2

one  two  three  four
1st  1.0  4.0    5.0   8.0
2nd  2.0  3.0    6.0   7.0
3rd  3.0  2.0    7.0   6.0
4th  4.0  1.0    8.0   5.0

In [28]:
abc

one  two  three  four
1st  1.0  4.0    5.0   8.0
2nd  2.0  3.0    6.0   7.0
3rd  3.0  2.0    7.0   6.0
4th  4.0  1.0    8.0   5.0

* 리스트로 구현한 DataFrame 과 딕셔너리로 구현한 DataFrame을 동일한 결과값으로 나타내었음

### Series로 DataFrame 만들기

In [29]:
a1 = {'a':1, 'b':2.,'c':3}
ddr = pd.DataFrame(a1)
#한줄짜리로 구성되어있을 경우 DataFrame으로 만들지 못함!

ValueError: If using all scalar values, you must pass an index

In [30]:
h = [1.0, 2.0, 3.0, 4.0]
pd.DataFrame(h)

0
0  1.0
1  2.0
2  3.0
3  4.0

#### 딕셔너리로 한줄짜리 DataFrame (X) 리스트로 한줄짜리 DataFrame (O) 가능!

- 딕셔너리의 key가 행인지 열인지 구분할 수 없기 때문임

In [31]:
a1 = {'a':1, 'b':2.,'c':3}
a1s = pd.Series(a1)
a1s

a    1.0
b    2.0
c    3.0
dtype: float64

- 딕셔너리로 시리즈 만들기 (O) 가능!

- 딕셔너리로 시리즈를 만든 뒤, 시리즈를 DataFrame으로 만드는 것이 가능한가?

In [32]:
pd.DataFrame(a1s) #가능하다! 딕셔너리를 DataFrame으로 만들기위한 우회적인 방법

0
a  1.0
b  2.0
c  3.0

* key값이 인덱스로 적용되고 이름을 주게되면 columns의 이름으로 적용된다. 

In [33]:
a1s = pd.Series(a1, name='sample1')
ddr = pd.DataFrame(a1s)
ddr

sample1
a      1.0
b      2.0
c      3.0

In [34]:
a1s = pd.Series(a1, name='sample1')
a2s = pd.Series(a1, name='sample2')
ddr = pd.DataFrame([a1s,a2s])
ddr

a    b    c
sample1  1.0  2.0  3.0
sample2  1.0  2.0  3.0

* 열이 붙는 것이 아니라 행이 추가가 된다.

- 열추가가 된 것 처럼 결과값을 내고 싶다면?

In [35]:
ddr.T

sample1  sample2
a      1.0      1.0
b      2.0      2.0
c      3.0      3.0

### Numpy를 이용한 DataFrame 만들기

In [36]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##### reshape ==> 재배치를 의미함 .reshape(행, 열)

In [37]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

* 0부터 12까지의 수를 3X4 3바이4배열로 배치

In [38]:
df = pd.DataFrame(np.arange(12).reshape(3,4),
                 index = ['Ohio', 'Colorado','New York'],
                 columns = ['one', 'two', 'three','four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [39]:
f = [1.0 , 2.0, 3.0, 4.0, 4.0, 3.0, 2.0, 1.0, 5.0, 6.0, 7.0, 8.0, 8.0, 7.0, 6.0, 5.0]
f

[1.0,
 2.0,
 3.0,
 4.0,
 4.0,
 3.0,
 2.0,
 1.0,
 5.0,
 6.0,
 7.0,
 8.0,
 8.0,
 7.0,
 6.0,
 5.0]

In [41]:
f.reshape(4,4)

AttributeError: 'list' object has no attribute 'reshape'

#### 바로 reshape를 사용할 수 있는 방법은 없음

In [43]:
f2= np.array(f)
f2

array([1., 2., 3., 4., 4., 3., 2., 1., 5., 6., 7., 8., 8., 7., 6., 5.])

* 리스트를 넘파이로 변환한 뒤, reshape를 사용하면 적용가능
* 넘파이가 데이터프레임으로 만들 수 있는 재료로 쓰일 수 있다

In [50]:
f3= np.array(f2).reshape(4,4)
f3

array([[1., 2., 3., 4.],
       [4., 3., 2., 1.],
       [5., 6., 7., 8.],
       [8., 7., 6., 5.]])

In [51]:
pd.DataFrame(f3)

0    1    2    3
0  1.0  2.0  3.0  4.0
1  4.0  3.0  2.0  1.0
2  5.0  6.0  7.0  8.0
3  8.0  7.0  6.0  5.0

#### 연습문제 [1]

In [46]:
df = pd.DataFrame(np.arange(12).reshape(3,4),
                 index = ['Ohio', 'Colorado','New York'],
                 columns = ['one', 'two', 'three','four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [71]:
df.loc['New York']

one       8
two       9
three    10
four     11
Name: New York, dtype: int32

In [73]:
df[['one','two','three','four']].loc['New York']

one       8
two       9
three    10
four     11
Name: New York, dtype: int32

In [74]:
df[['one','two','three','four']].iloc[2]

one       8
two       9
three    10
four     11
Name: New York, dtype: int32

In [50]:
df.iloc[2]

one       8
two       9
three    10
four     11
Name: New York, dtype: int32

In [79]:
df.iloc[1,1:3]

two      5
three    6
Name: Colorado, dtype: int32

In [80]:
df.iloc[1,[1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [58]:
df.loc['Colorado','two':'three']

two      5
three    6
Name: Colorado, dtype: int32

In [60]:
df.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

#### 다음과 같은 표기도 가능

* 변수['열이름'].loc['행이름']
* 변수['열이름'.iloc['행순번']]

In [76]:
df[['two','three']].loc['Colorado']

two      5
three    6
Name: Colorado, dtype: int32

In [77]:
df[['two','three']].iloc[1]

two      5
three    6
Name: Colorado, dtype: int32

In [78]:
df[['two']].iloc[1]

two    5
Name: Colorado, dtype: int32

#### 연습문제 [2]

In [82]:
pd.DataFrame(df, 
             index = ['Colorado','Ohio'],
             columns = ['three','one'])

three  one
Colorado      6    4
Ohio          2    0

In [83]:
df.loc[['Colorado','Ohio'],['three','one']]

three  one
Colorado      6    4
Ohio          2    0

In [85]:
df.iloc[[1,0],[2,0]]

three  one
Colorado      6    4
Ohio          2    0

#### 새로운 표기법 적용한 것은?

In [89]:
df[['three','one']].loc[['Colorado','Ohio']]

three  one
Colorado      6    4
Ohio          2    0

In [91]:
df[['three','one']].iloc[[1,0]]

three  one
Colorado      6    4
Ohio          2    0

#### 연습문제 [3]

In [107]:
df.loc[['Ohio','Colorado'],'two']

Ohio        1
Colorado    5
Name: two, dtype: int32

In [111]:
df.iloc[[0,1],1]

Ohio        1
Colorado    5
Name: two, dtype: int32

In [112]:
df['two'].loc[['Ohio','Colorado']]

Ohio        1
Colorado    5
Name: two, dtype: int32

In [114]:
df['two'].iloc[[0,1]]

Ohio        1
Colorado    5
Name: two, dtype: int32

#### column 선택 하는 건 DataFrame 에서 Series Data 추출하는 것

#### 연습문제 [4]

In [122]:
df.loc[['Colorado','New York'],['one','two']]

one  two
Colorado    4    5
New York    8    9

In [123]:
df.loc['Colorado':'New York','one':'two']

one  two
Colorado    4    5
New York    8    9

In [119]:
df.iloc[1:3,0:2]

one  two
Colorado    4    5
New York    8    9

In [121]:
df.iloc[[1,2],[0,1]]

one  two
Colorado    4    5
New York    8    9

In [135]:
df[['one','two']].loc[['Colorado','New York']]

one  two
Colorado    4    5
New York    8    9

In [140]:
df['one':'two'].loc['Colorado':'New York']

KeyError: 'one'

In [141]:
df[['one','two']].loc['Colorado':'New York']

one  two
Colorado    4    5
New York    8    9

In [133]:
df[['one','two']].loc[['Colorado','New York']]

one  two
Colorado    4    5
New York    8    9

In [137]:
df[['one','two']].iloc[[1,2]]

one  two
Colorado    4    5
New York    8    9

In [145]:
df[['one','two']].iloc[1:3]

one  two
Colorado    4    5
New York    8    9

#### 번외 ) 오류분석

In [147]:
df[0:2].iloc[1:3]

one  two  three  four
Colorado    4    5      6     7

In [143]:
df[0:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [148]:
df.iloc[1:3]

one  two  three  four
Colorado    4    5      6     7
New York    8    9     10    11

* df[0:2] 와 df.iloc[1:3] 의 결과 값의 공통분모를 추출하게 된다.